### ISSUE TITLE
绝对布局不好

### ISSUE THREAD

**Issue by weituotian** [minirefresh/minirefresh#13]
已经不能改绝对布局了么？

上下两个列表，列表之间还有其它的html元素。

那么我每次修改都得去修改那个top的px

多麻烦

**Comment by dailc** [comment]
事实上绝对布局是目前经过实验觉得相对较优的一直方案。
如果觉得有更好的可以自行尝试下，也欢迎分享出来，如果合理，可有考虑合并。
