### ISSUE TITLE
加载样式很棒，如何通过设置，只需下拉加载功能，不要上拉加载的功能

### ISSUE THREAD

**Issue by YeWills** [minirefresh/minirefresh#14]
由于项目历史原因，已经有了上拉加载功能，这部分代码不打算动，现在只需要做一个下拉加载的功能，能否通过设置关闭上拉加载功能，且不影响项目原来的上拉加载功能

**Comment by dailc** [comment]
up.isLock为true的话就会关闭上拉加载功能。
具体是否冲突需要实际页面才可验证

**Comment by YeWills** [comment]
之前我看了你们的api文档，https://minirefresh.github.io/minirefresh-doc/minirefresh-doc/api/api_minirefresh.html  也用了你说了这个方法，不过当上拉加载的时候，上拉加载的背景框和飞往顶部的图标不能隐藏，刚才想到了一个简单粗暴的方法，直接在html中，把这两个对应的节点，隐藏了：
`
.minirefresh-upwrap{
				display: none;
			}
			.minirefresh-totop{
				display: none;
			}
`
完美解决了问题，
感谢作者团队，我们移动项目是基于mui框架了，居然你们的示例也有基于mui的示例，示例太强大了

**Comment by dailc** [comment]
totop 也有配置项的。(default主题的使用文档中) up.toTop.isEnable 为false就可关闭了
背景框的话可能是没有考虑到，你可以暂时这样处理
