### ISSUE TITLE
up,down的回调中不用setTimeout无法下拉的问题

### ISSUE THREAD

**Issue by shixiangweii** [minirefresh/minirefresh#15]
当下拉的回调中，往dom追加元素的时候，如果没有setTimeout，数据追加后，下拉和上拉就失效了，
下拉就拉不动了，无法出现下拉头部的提示，
上拉也无法出现提示

`                setTimeout(function() {

                    if( $config.isReset){
                        appendTestData(json.data,listDom, 10, true);
                        miniRefresh.endDownLoading(true);
                    }else{
                        maxDataSize=json.data.total;
                        appendTestData(json.data,listDom, 10);
                        miniRefresh.endUpLoading(listDom.children.length >= maxDataSize ? true : false);

                    }

                },requestDelayTime);`

**Comment by dailc** [comment]
最好提供下还原页面呢。预估可能是代码逻辑问题。

**Comment by shixiangweii** [comment]
谢谢回答！
是的如大神所说，是我自己逻辑搞乱了，没仔细看文档，理解错误了。。。
多谢回答
