### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by CharlinFeng** [minirefresh/minirefresh#16]
1.requireJS下，经常提示：并不是每次，但频率非常高：
Uncaught ReferenceError: MiniRefreshTools is not defined
    at minirefresh.theme.applet.min.js:7

2.在顶部可以使用鼠标拖拽，能否实现，任意位置可以支持鼠标拖拽？

**Comment by dailc** [comment]
1.所有的主题都基于MiniRefreshTools全局对象（minirefresh.js运行后默认注册的全局对象）
2.请描述清晰点。 现在普通的鼠标拖拽是支持的吧。
