### ISSUE TITLE
有没有考虑引入reactjs

### ISSUE THREAD

**Issue by geekwill** [minirefresh/minirefresh#17]
有没有考虑引入reactjs

**Comment by dailc** [comment]
按目前预计的话，估计是待我找个时间段，封装个react版本的。
或者也可以大家贡献。。。

**Comment by dailc** [comment]
[https://github.com/minirefresh/minirefresh-react-examples](https://github.com/minirefresh/minirefresh-react-examples)

写了一个初步的示例，关于react中如何使用的。

后续完善。

**Comment by ilaipi** [comment]
@dailc 这个react的示例写的太复杂了 🤣
