### ISSUE TITLE
使用 isUseBodyScroll 后上拉加载和 onscroll 失效

### ISSUE THREAD

**Issue by shoyuf** [minirefresh/minirefresh#22]
demo：https://codepen.io/anon/pen/dJWZEB

打印出来的 scrollTop 全为 0，在桌面端 chrome 也无法加载更多了，但在移动端貌似是正常的

**Comment by dailc** [comment]
看起来像是在Iframe中使用`isUseBodyScroll: true`导致的bug，你可以设置`isUseBodyScroll: false`试试，我试了下这样并没问题

**Comment by shoyuf** [comment]
不在 iframe 也存在这个问题，你看下是我这边代码参数配置有问题吗？http://otmlr05hs.bkt.clouddn.com/minirefresh-issue.html

**Comment by dailc** [comment]
看了下，应该是`isUseBodyScroll: true`导致的bug，你可以设置`isUseBodyScroll: false`试试解决

**Comment by dailc** [comment]
isUseBodyScroll请不要在iframe情况下使用
