### ISSUE TITLE
头部组件重叠现象

### ISSUE THREAD

**Issue by sunlandong** [minirefresh/minirefresh#25]
当包含内容没有背景颜色的时候，这个时候，下拉组件和正文内容背景色一致，会出现重叠现象，建议修复。另外写了一个react版本的，有机会上传，嘿嘿

**Comment by dailc** [comment]
欢迎贡献🤝。  关于透明背景的，我在示例上区别下吧。

**Comment by dailc** [comment]
2.0.2已经默认将背景改成白色
