### ISSUE TITLE
使用masonry，导致移动一点点就触发ｕｐ事件

### ISSUE THREAD

**Issue by LiuXiao617111** [minirefresh/minirefresh#26]
使用ajax动态添加的数据，且使用了瀑布流（masonry）来布局，导致我的布局结构都是absolute定位的
![image](https://user-images.githubusercontent.com/8858358/34915639-b37735f8-f964-11e7-9b1c-0e1dfe147069.png)
然后测试发现只要滚动一点点，就触发了up事件
然后我把瀑布流去掉，就正常了。所以推测是定位问题。
![image](https://user-images.githubusercontent.com/8858358/34915680-59cf6cc2-f965-11e7-8345-c9a9d90e1cab.png)
还有这个样式问题，当然我自己覆盖了下就可以了。

**Comment by dailc** [comment]
经沟通，问题不是minirefresh造成的。并且已经解决。
