### ISSUE TITLE
咨询个问题

### ISSUE THREAD

**Issue by shunzizhan** [minirefresh/minirefresh#28]
最近有一个需求，就是从列表页中点击查看某一条商品，进入详情页之后，返回时，需要定位到刚看查看的位置，目前的做法是，在列表页中记录点击元素的`pageY`，返回到列表时，则用`scrollTo`，发现不论是`body`，还是配置的`container`元素都不起作用，不知道怎么去设定它滚到指定的位置
ps:将配置的`isUseBodyScroll`设置为true，`scrollTo`生效了，但是那个下拉刷新，则很卡，半天不回弹隐藏，

**Comment by dailc** [comment]
自带的scrollto方法不行么？

**Comment by shunzizhan** [comment]
可以了，哈哈，纠结了半天了，谢谢
