### ISSUE TITLE
可否解决fixed无效问题？

### ISSUE THREAD

**Issue by cbahai** [minirefresh/minirefresh#31]
这个刷新容器使用了transform，导致了fixed无效，可否解决呢？

**Comment by dailc** [comment]
fixed问题的是否有可还原的页面？

**Comment by cbahai** [comment]
子元素使用fixed定位都无效，你可以试试

```
<div id="minirefresh" class="minirefresh-wrap">
    <div class="minirefresh-scroll">
       fixed元素无效
    </div>
</div>
```

**Comment by dailc** [comment]
上拉中的toTop元素就是fixed布局的啊。

**Comment by cbahai** [comment]
```
<div id="minirefresh" class="minirefresh-wrap">
    <div class="minirefresh-scroll">
       fixed元素无效
    </div>
    fixed元素有效(toTop元素是加在这里的)
</div>
```

**Comment by dailc** [comment]
如果是想在`minirefresh-scroll`中放fixed的话，很遗憾，因为`minirefresh-scroll`中的下拉动画是基于transform进行的。（还与不同主题有关，有的主题是没有`minirefresh-scroll`的transform动画的）

然后说下：

1. 现在的h5下拉刷新动画基本都是基于transform动画进行的（因为可以进行3d加速，变为复合层，避免回流，重绘，提升性能）

2. 使用transform和fixed冲突可以算是特性了（不仅仅是bug），参考[https://stackoverflow.com/questions/2637058/positions-fixed-doesnt-work-when-using-webkit-transform](https://stackoverflow.com/questions/2637058/positions-fixed-doesnt-work-when-using-webkit-transform)

3. 如果强行要在minirefresh-scroll中使用fixed，建议可以自行拓展主题，如基于drawerslider主题拓展，并将minirefresh-scroll的3d加速去掉

总结就是：
自行拓展主题，只要是那种minirefresh-scroll无需位移动画的主题都可以不使用3d加速，从而不使用transform，从而让内部可以使用fixed

**Comment by zhaoweihz** [comment]
也碰到这个坑了 建议增加个css2拉动支持
