### ISSUE TITLE
有个加载效果是,上拉加载数据的时候,希望页面每次上拉至还剩下百分之20的时候,就加载数据,而不是拉到页面底部了才加载.

### ISSUE THREAD

**Issue by KingPengZero** [minirefresh/minirefresh#5]

**Comment by KingPengZero** [comment]
有个加载效果是,上拉加载数据的时候,希望页面每次上拉至还剩下百分之20的时候,就加载数据,而不是拉到页面底部了才加载.
第二个需求是,如果没有数据请求回来的时候,如何不出现loading的效果.

**Comment by dailc** [comment]
第一点： 
```js
up: {
    // 可以修改成对应的offset，代表离底部多远就开始加载，可以自己通过屏幕高度换算下
    offset: 600
}
````

第2点：  能否再描述清晰一点？
loading是加载中时出现的，不知道你想实现怎么样的效果。
是想要加载时不出现loading么？如果这样的话配置`up.isShowUpLoading`为`false`即可

**Comment by dailc** [comment]
如果没有其它问题了，这个issue就关闭了。
