### ISSUE TITLE
如何与iscroll整合

### ISSUE THREAD

**Issue by ivanberry** [minirefresh/minirefresh#6]
如何与iscroll整合？

**Comment by dailc** [comment]
请描述的清晰一点呢。
如果是指在IScroll页面中嵌套minirefresh的话，我记得showcase中有类似的示例的（showcse中是swipe以及老本的iscroll4嵌套，你可以换成对应的iscroll试试，如果有问题可以反馈）

另外，后续更新可以单独新增一个iscroll嵌套示例

**Comment by ivanberry** [comment]
好，谢谢，我自己好好尝试下

**Comment by dailc** [comment]
没其它问题的话就关闭了，上次沟通的结论是：

- 如果是横向的IScroll + 多个纵向的minirefresh，这样嵌套是没问题的

- 不建议纵向的IScroll和minirefresh同时在一个页面中使用
