### ISSUE TITLE
为什么初始化的时候回默认执行上拉的方法

### ISSUE THREAD

**Issue by yanghui-gao** [minirefresh/minirefresh#9]
页面可以铺满数据,在初始化时会默认执行上拉方法,导致加载20条数据
`this.refresh = new MiniRefresh({
       container: '#minirefresh',
       down: {
         callback: this.getlistmessage_down,
         isAuto: true
       },
       up: {
         callback: this.getlistmessage_up,
//         isLock: true
         isAuto:false
       }
     })`
配置是这样的,确认数据可以铺满屏幕

**Comment by dailc** [comment]
按照你这个配置项应该是这样的吧：
1.初始化执行downcallback
2如果执行完后，数据未满屏，会自动执行upcallback

请问你遇到的问题是怎么样的？
是初始化会先下拉，但是下拉完后紧接着会上拉么？
有没有在线示例？ 。官方的showcase能否还原类似问题？

**Comment by yanghui-gao** [comment]
对的,初始化会自动执行一次downcallback,执行完成后确认数据可以铺满屏幕,但是还是会默认执行一次upcallback,这是我不能明白的;再次确认执行downcallback后数据可以铺满屏幕.

![downandup](https://user-images.githubusercontent.com/19601875/31365964-3691816e-ad34-11e7-9ce4-40fdf100045b.gif)

**Comment by dailc** [comment]
注意下示例图片中的进度条。
看起来应该是： 当你滑动到距离底部up.offset时自动触发了上拉加载。

你可以更改下up.offset来控制上拉加载的响应范围

**Comment by yanghui-gao** [comment]
问题解决的办法是我更改了行高,问题所在应该还是在计算是否刷新这个地方吧?虽然第10条数据只超出屏幕一半,但是也确实铺满了整个屏幕.小弟愚见,如果说错了望见谅(图中示例应该是已经又触发上拉加载,应该是20条+)

**Comment by dailc** [comment]
你可以发一个在线示例，因为我在showcase中还原不出来
